Feature/initial configuration
rvillaab/survey pull request #1
Opened 2021-06-02 21:42 UTC by rvillaab

2021-06-09 19:45 UTC, RicardoBeltranRamirez requested changes
Just a few comments

2021-06-09 19:45 UTC, RicardoBeltranRamirez commented on pckg/service/questionService.go
> +}
`type QuestionServiceImpl struct {	
  dao QuestionDao
}`

`type QuestionDao struct {
	DB *sql.DB
}`


`func (qstImpl QuestionServiceImpl) CreateQuestion(question ent.Question) (ent.Question, error){
err := qstimpl.dao.CreateQuestion(question)	
if err != nil{
   return nil, err
}
return question, nil
}`

2021-06-09 19:45 UTC, RicardoBeltranRamirez commented on pckg/test/mocks/mockQuestionService.go
> +	m.MockGetAllQuestionsFunc = f
`if m.MockGetAllQuestionsFunc != nil{
      return m.MockGetAllQuestionsFunc = f
}
return nil
´

2021-06-10 19:54 UTC, rvillaab commented on pckg/service/questionService.go
> +}
Done!

2021-06-10 19:54 UTC, rvillaab commented on pckg/test/mocks/mockQuestionService.go
> +	m.MockGetAllQuestionsFunc = f
Done!

2021-06-10 20:43 UTC, RicardoBeltranRamirez approved these changes
Excellent! LGTM

2021-06-10 20:44 UTC, merged